### ISSUE TITLE
Why not use Constructor ?

### ISSUE THREAD

**Issue by NaturalSelect** [hanbings/CatPawServer#1]
https://github.com/hanbings/CatPawServer/blob/13905f058ae9ba7b5e6c2b09f016855dc3ea8ea6/src/main/java/com/nanokylin/catpawserver/service/ThreadPoolService.java#L10

A constructor will be better and more flexible

**Comment by hanbings** [comment]
First thank you very much for your Issue
很感谢你的Issue
An independent method is used here instead of a constructor. The reason is to avoid repeating the constructor when using this class/interface multiple times
这里使用了一个独立方法 而不使用构造方法 原因是为了避免多次使用这个类/接口时重复执行构造方法
As you can see, this method has no parameters, which means that this method cannot be **overload**
如你所见 这个方法没有参数 这就意味着无法对此方法进行**重载**
Whether I want to execute this construction method (isn’t it weird to say that the construction method should be executed during construction), it will execute
无论我想不想执行这个构造方法（这样说是不是有点奇怪 构造方法应该在构造时执行） 它都将执行
If there is a better way to solve this problem, please let me know and I will rewrite (review/refact?) the code
如果有更好的写法来解决这个问题请告知我，我将会重新编写这些代码
Thank you again for your Issue
再次感谢你的Issue

**Comment by NaturalSelect** [comment]
Why the constructor will be repeated?

**Comment by hanbings** [comment]
The new implementation has been completed
目前已经完成了新的实现
Path: CatPawServer/src/main/java/com/nanokylin/catpawserver/service/impl/ThreadPoolServiceReforgeImpl.java
路径: CatPawServer/src/main/java/com/nanokylin/catpawserver/service/impl/ThreadPoolServiceReforgeImpl.java
If the problem is resolved, the old implementation will be cleaned up soon
如果问题得到解决 不久后将会进行旧的实现的清理工作
Thank
谢谢

**Comment by NaturalSelect** [comment]
https://github.com/hanbings/CatPawServer/blob/b9cdcdae27b1fc75ee6e40a9efe269dfdd546122/src/main/java/com/nanokylin/catpawserver/service/impl/ThreadPoolServiceReforgeImpl.java#L27
You should call it in constructor.
And,you needn't to include it in interface.

**Comment by hanbings** [comment]
I have completely removed initThreadPoolService() in the new code and provided two construction methods to avoid reuse
我已经在新的代码里把initThreadPoolService()完全去掉了 并且提供了两个构造方法避免复用
Thank you again for your Issue
再次感谢你的Issue
